name: Macos build

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: '01 01 * * 6'    # Run every Saturday

jobs:

  list-gcc:
    name: list available perl versions
    runs-on: macos-latest
    steps:
      - uses: shogo82148/actions-setup-perl@v1
      - id: set-matrix
        name: list available perl versions
        shell: perl {0}
        run: |
          use Actions::Core;

          print "Version available\n";
          my @versions = perl_versions();
          for my $v (@versions) {
            print "\t$v\n";
          }
          # Don't want anything less then 5.8
          @versions = grep { ! /^5\.6\.*/ } @versions;
          set_output(matrix => {'perl'       => [@versions],
                                'build-zlib' => [0, 1],
                                'ccflags'    => ['-Werror', '-Werror -Wc++-compat'],
                                'compiler'   => ['gcc'],
                               },
                    );
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  run-gcc:
    name: Perl ${{ matrix.perl }} BUILD_ZLIB:${{matrix.build-zlib}} CC="${{matrix.compiler}}" CCFLAGS:${{matrix.ccflags}}
    runs-on: macos-latest
    needs: list-gcc
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.list-gcc.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v6
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: Perl version
        run: perl -V
      - name: Install dependencies
        run: cpanm --quiet --installdeps --notest .
      - name: Build
        run: |
          flags=$( perl -MConfig -e 'print $Config::Config{ccflags}' )
          perl Makefile.PL CCFLAGS="$flags ${{matrix.ccflags}}" CC="${{matrix.compiler}}" && make
        env:
          BUILD_ZLIB: ${{matrix.build-zlib}}
      - name: Test
        run: make test



  list-gpp:
    name: list available perl versions
    runs-on: macos-latest
    steps:
      - uses: shogo82148/actions-setup-perl@v1
      - id: set-matrix
        name: list available perl versions
        shell: perl {0}
        run: |
          use Actions::Core;

          print "Version available\n";
          my @versions = perl_versions();
          for my $v (@versions) {
            print "\t$v\n";
          }
          # Don't want anything less then 5.8
          @versions = grep { ! /^5\.6\.*/ } @versions;
          set_output(matrix => {'perl'       => [@versions],
                                'build-zlib' => [0, 1],
                                'ccflags'    => ['-Werror', '-Werror -xc++'],
                                'compiler'   => ['g++'],
                               },
                    );
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  run-gpp:
    name: Perl ${{ matrix.perl }} BUILD_ZLIB:${{matrix.build-zlib}} CC="${{matrix.compiler}}" CCFLAGS:${{matrix.ccflags}}
    runs-on: macos-latest
    needs: list-gcc
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.list-gpp.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v6
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: Perl version
        run: perl -V
      - name: Install dependencies
        run: cpanm --quiet --installdeps --notest .
      - name: Build
        run: |
          flags=$( perl -MConfig -e 'print $Config::Config{ccflags}' )
          perl Makefile.PL CCFLAGS="$flags ${{matrix.ccflags}}" CC="${{matrix.compiler}}" && make
        env:
          BUILD_ZLIB: ${{matrix.build-zlib}}
      - name: Test
        run: make test
